### ISSUE TITLE
lepsi animace zasahu

### ISSUE THREAD

**Issue by vvolhejn** [allemansratten/LD44#11]
momentalne se jen barva zmeni na cervenou, takze nekolikanasobne zasahy se spatne poznaji. mohla by treba odletet koncetina, o kterou clovek prisel, nebo by se mohlo ukazat bliknuti

**Comment by zouharvi** [comment]
Mrknu na to. :slightly_smiling_face:

**Comment by zouharvi** [comment]
Resolved in 5e0b1f5c807c400a1490be76ff3cabf9fe0b799e
